Feature/main feature
pacyL2K19/weather-app pull request #2
Opened 2021-05-20 20:39 UTC by pacyL2K19

# The aim of this PR
- Build the `HTML` through  js 
- Consume the API to fetch weather info 
- Setup the linter 
- Update minimal style to the main boxes

2021-05-21 07:05 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Amazing work on this PR. Your app looks good.
### Well done 🌵 🌵 🌵 
- Codebase is modularised
- Use of ES6 syntax
- A user can search weather for a particular city
- There's a toggle button for changing temperature units

### Changes to make 🙅🏿 🙅🏿 🙅🏿 
- You have comments in your codebase. Comments make the code look ugly.
- Add error handling for the API request.

### Nice to have
- Move the temperature display below the date display. I couldn't see the result and was about to ask for it as a change to be made.


### Martin Afani
#### Slack: whiz25

2021-05-21 07:05 UTC, afanimartin commented on src/index.js
> +    //   console.log('here');
- Remove this comment and any other. Comments make the codebase to look ugly.

2021-05-21 07:05 UTC, afanimartin commented on src/scripts/render.js
> +
- Remove this comment

2021-05-22 04:10 UTC, voscarmv approved these changes
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-05-22 07:15 UTC, merged

2021-05-29 15:36 UTC, pacyL2K19 reviewed
# [Personal] Additional :heavy_plus_sign: 
- Avoid ES5 symtaxes as much as possible